### PR TITLE
Create CJS templates

### PR DESCRIPTION
**Pull request by spencerwilson-optimizely**

### CODE REVIEW

**Comment by tylerbrandt** [comment]
Who's the audience for this? AFAIK external (success) teams always file in BUG, so this template wouldn't apply. Furthermore, I think the only people that regularly file tickets in CJS are CJS team members, for which the questions in "Impact" don't really apply.

**Comment by asaschachar** [comment]
@tylerbrandt good points. Do you have any ideas for how we can get better information for bugs filed in the broad BUG project?

And are there any templates you _would_ want for tickets filed by the CJS team?

**Comment by spencerwilson-optimizely** [comment]
Am closing due to the feedback above, because I really wanted the content in the template to be seen by bug filers. I considered adapting the content for a BUG template, but I couldn't think of a decent way to format it when folks might also be filing things that are METRICS- and WEB-bound too.

**Comment by asaschachar** [comment]
Thanks Spencer for at least exploring this option. It is an interesting problem because when people initially file a bug, they don't always know what part of the codebase is at fault, so sometimes it's unclear if it is a Client issue. If you have other ideas for how to fix this problem, let me know!

**Pull request closed without merging**
